version: "3.9"
# service name: postgres
services:
  postgres:
    container_name: conference.pg
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: conference
    ports:
        - 5432:5432
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    networks:
        - conference-net
# service name: conference
  conference:
    container_name: conference.app
    build: ./conference-api
    environment:
        SERVER_PORT: 3000
        KEYCLOAK_AUTH-SERVER-URL: http://keycloak:8080/
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/conference
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
        BANK_URL: http://bank:3001
    ports:
        - 3000:3000
    depends_on:
        - postgres
        - keycloak
    networks:
        - conference-net
  # service name: bank
  bank:
    container_name: conference.bank
    build: ./conference-bank
    environment:
        SERVER_PORT: 3001
    ports:
        - 3001:3001
    depends_on:
        - keycloak
    networks:
        - conference-net
  # service name: keycloak
  keycloak:
    container_name: conference.keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        DB_VENDOR: h2
    command:
        - start-dev --features=scripts --import-realm --hostname-url=http://localhost:8090
    ports:
        - 8090:8080
    volumes:
        - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    networks:
        - conference-net
  # service name: prometheus
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: conference.prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - conference-net
  # service name: grafana
  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: conference.grafana
    depends_on:
      - prometheus
    ports:
      - "3002:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - conference-net
networks:
    conference-net:
        driver: bridge